# Core utilities
brew "git"          # Version control
brew "zsh"          # Shell
brew "curl"         # Command line tool for data transfer
brew "htop"         # Inteactive process viewer

# C Development Tools
brew "make"          # Tool to build and manage projects
brew "pkg-config"    # Helper tool for managing library compile/link flags
brew "gdb"           # GNU debugger for debugging C programs

# Terminal Essentials 
cask "ghostty"      # Terminal emulator 
brew "neovim"

# GUI tools
cask "aerospace"   # Developer app for your workflow
cask "raycast"     # App launcher and productivity tool
